---
abstract: 'turn on Unicode - all of it'
author:
  - 'Michael Schwern <mschwern@cpan.org>'
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  PerlIO: '0'
  Test::Fatal: '0'
  Test::More: '0.96'
  Test::Warn: '0'
  autodie: '0'
  version: '0.77'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: utf8-all
no_index:
  directory:
    - corpus
    - inc
    - examples
requires:
  Encode: '0'
  Import::Into: '0'
  Symbol: '0'
  charnames: '0'
  feature: '0'
  open: '0'
  parent: '0'
  perl: '5.010'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/doherty/utf8-all/issues
  homepage: http://metacpan.org/release/utf8-all/
  repository: git://github.com/doherty/utf8-all.git
version: '0.013'
