---
abstract: 'turn on unicode. All of it.'
author:
  - 'Michael Schwern <mschwern@cpan.org>'
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  PerlIO: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: utf8-all
requires:
  Encode: 0
  open: 0
  parent: 0
  perl: 5.010
  utf8: 0
resources:
  bugtracker: https://github.com/doherty/utf8-all/issues
  repository: git://github.com/doherty/utf8-all.git
version: 0.001
