---
abstract: 'turn on Unicode - all of it'
author:
  - 'Michael Schwern <mschwern@cpan.org>'
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  PerlIO: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: utf8-all
no_index:
  directory:
    - corpus
requires:
  Encode: 0
  charnames: 0
  open: 0
  parent: 0
  perl: 5.010
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/utf8-all/issues
  homepage: http://metacpan.org/release/utf8-all/
  repository: git://github.com/doherty/utf8-all.git
version: 0.004
